# name: Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # Setup keyy
#       - run: set -eu
#       - run: mkdir "$HOME/.ssh"
#       - run: echo "${{ secrets.secret_key }}" > "$HOME/.ssh/secret_key" # secret_key - название секрета
#       - run: chmod 600 "$HOME/.ssh/secret_key"
#       - run: composer install && rsync -e "ssh -i $HOME/.ssh/secret_key -o StrictHostKeyChecking=no" --archive --compress . nomokoiw@nomokoiw.beget.tech:/home/n/nomokoiw/stand2/public_html/back # полный путь до папки, куда нужно скопировать файлы

#         # Deploy db
#       - name: Deploy database
#         run: |
#           sudo /etc/init.d/mysql start
#           mysql -h nomokoiw.beget.tech -unomokoiw_efes -pwxCE6A_G nomokoiw_efes < db/init.sql
